### ISSUE TITLE
mangal source for new data?

### ISSUE THREAD

**Issue by seltmann** [jhpoelen/eol-globi-data#157] opened 2015-08-09 18:15 UTC
seen this?

http://mangal.uqar.ca/

**Comment by jhpoelen** [comment] 2015-08-10 15:31
Yep, I've seen mangal and I've been in touch with Tim Poissot @tpoisot and hoping to get an integration going as soon at the time is right. We tried some approaches #81 and I believe that the current approach is for Mangal (has since moved to http://mangal.io) to produce and publish an darwin core archive that would be ingested by GloBI (and then by EOL and other GloBI consumers).

Thanks for the pointer @seltmann  . . . please keep 'em coming!

(closing this issue as it is a duplicate of #81)

**Closed by jhpoelen** 2015-08-10 15:31 UTC
