### ISSUE TITLE
suspicious marine taxonomic classification involving Fenestraria rhopalophylla

### ISSUE THREAD

**Issue by jsimons9** [jhpoelen/eol-globi-data#292] opened 2017-04-20 18:19 UTC
I recently got an inquiry from a user at the GSMFC of the GoMexSI database about a name of an organism that was reported as diet of M. undulatus in Senol’s dissertation raw data.  The name is:  Fenestraria rhopalophylla.  It appears to be a succulent from South Africa.  I could not find it in ITIS.  It appears a large number of times in many species in Senol’s data, so it appears to be something fairly common.  I searched the rest of GloBI and interestingly it also appeared in the diets of a sole (Limanda aspera) from the Bering Sea – diet data collected by NOAA.  In all, there were 1024 instances of Fenestraria rhopalophylla in the GoMexSI/GloBI database.

**Comment by jhpoelen** [comment] 2017-04-21 18:07
Thanks for reporting this issue.

A search for taxonomic mapping to taxon ```Fenestraria rhopalophylla``` yielded various names involving "Sand" (see below). It appears that a common name for the species as reported on EOL taxon page at http://eol.org/pages/2942517/names/common_names includes "Sand" as a common name. An attempt to reproduce this behavior failed, suggesting that the name "Sand" no longer resolves to said species.

I'll remove the recorded taxonomic links, so that the names can be resolved again. Will close issue once the changes have propagated.

Hope this helps and thanks for your patience. 

PS. Note that NODC:8857041701 taxon point to both ```Sand sole Psettichthys melanostictus``` and ```Misc Flatfish```. ```Misc Flatfish``` was resolved to Fenestraria rhopalophylla because GloBI assumed that taxon ids are unique point to a single taxon concept. Also GloBI uses taxon ids first, and taxon name strings second in name resolving. In the end, this explains why ```Misc Flatfish``` resolved to Fenestraria rhopalophylla. 

from taxonMap.tsv (see http://globalbioticinteractions.org/references)
```tsv
providedId providedName resolvedId resolvedName
	Sand siliceous	EOL:2942517	Fenestraria rhopalophylla
	Sand siliceous	OTT:613311	Fenestraria rhopalophylla
	Sand siliceous	GBIF:7329187	Fenestraria rhopalophylla
	Sand siliceous	NCBI:188818	Fenestraria rhopalophylla
	Sand	EOL:2942517	Fenestraria rhopalophylla
	Sand	OTT:613311	Fenestraria rhopalophylla
	Sand	GBIF:7329187	Fenestraria rhopalophylla
	Sand	NCBI:188818	Fenestraria rhopalophylla
	Sand calcareous	EOL:2942517	Fenestraria rhopalophylla
	Sand calcareous	OTT:613311	Fenestraria rhopalophylla
	Sand calcareous	GBIF:7329187	Fenestraria rhopalophylla
	Sand calcareous	NCBI:188818	Fenestraria rhopalophylla
	SAND	EOL:2942517	Fenestraria rhopalophylla
	SAND	OTT:613311	Fenestraria rhopalophylla
	SAND	GBIF:7329187	Fenestraria rhopalophylla
	SAND	NCBI:188818	Fenestraria rhopalophylla
	sand	EOL:2942517	Fenestraria rhopalophylla
	sand	OTT:613311	Fenestraria rhopalophylla
	sand	GBIF:7329187	Fenestraria rhopalophylla
	sand	NCBI:188818	Fenestraria rhopalophylla
	Sand (muddy)	EOL:2942517	Fenestraria rhopalophylla
	Sand (muddy)	OTT:613311	Fenestraria rhopalophylla
	Sand (muddy)	GBIF:7329187	Fenestraria rhopalophylla
	Sand (muddy)	NCBI:188818	Fenestraria rhopalophylla
NODC:8857041701	Sand sole Psettichthys melanostictus	EOL:2942517	Fenestraria rhopalophylla
NODC:8857041701	Sand sole Psettichthys melanostictus	OTT:613311	Fenestraria rhopalophylla
NODC:8857041701	Sand sole Psettichthys melanostictus	GBIF:7329187	Fenestraria rhopalophylla
NODC:8857041701	Sand sole Psettichthys melanostictus	NCBI:188818	Fenestraria rhopalophylla
NODC:8857041701	Misc Flatfish	EOL:2942517	Fenestraria rhopalophylla
NODC:8857041701	Misc Flatfish	OTT:613311	Fenestraria rhopalophylla
NODC:8857041701	Misc Flatfish	GBIF:7329187	Fenestraria rhopalophylla
NODC:8857041701	Misc Flatfish	NCBI:188818	Fenestraria rhopalophylla
```

![fenestrariaeol2942517](https://cloud.githubusercontent.com/assets/1084872/25290201/bc2711de-2681-11e7-9e1e-6882f718b97f.png)

**Comment by jsimons9** [comment] 2017-04-21 18:21
Hi Jorrit,

  I am a little confused.  It appears that Fenestraria rhopalophylla
Is a succulent that is form south Africa.  Some food item from Mad Island Marsh (and looks like the Bering Sea) have been mis-identified as Fenestraria rhopalophylla.

Jim

**Comment by jhpoelen** [comment] 2017-04-21 18:28
Yep, Fenestraria rhopalophylla Is a succulent that is form south Africa. And... a reported common name for the succulent is "Sand". The marine datasets that you referred to contained diet items that started with "Sand", which then mistakenly resolved to the succulent. All in all a bug in the taxonomic name resolution. Please let me know if you need more info, happy to discuss by voice.

**Comment by jsimons9** [comment] 2017-04-21 18:33
OK, I get it now.  So the food item should be sand – that make sense.

Thanks for the clarification.

Jim

**Comment by jhpoelen** [comment] 2017-04-24 15:22
Changes have propagated and Fenestraria sp. is no longer reported as food items for said fish (see attached screenshot).

![fenestraria](https://cloud.githubusercontent.com/assets/1084872/25344479/1b7df534-28c7-11e7-846e-dae304a2158a.png)

**Closed by jhpoelen** 2017-04-24 15:22 UTC
Labels: needs data review
