### ISSUE TITLE
User agent blocking for bulk downloads?

### ISSUE THREAD

**Issue by ethanwhite** [jhpoelen/eol-globi-data#345] opened 2018-02-24 17:28 UTC
We've been trying to add the GLOBI data to the our `retriever` software to allow it to be automatically downloaded and installed by our users: https://github.com/weecology/retriever/pull/1096

However, we've run into an issue in that the data dump (the one at https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/interactions.tsv.gz) is 403ing when we try to download it from inside Python (https://github.com/weecology/retriever/pull/1096#issuecomment-368244126).

I'm guessing this means the user agent is being blocked and wanted to see if this was something that we could workout so that we could access the data programmatically. Thanks in advance for any thoughts/help.

**Comment by jhpoelen** [comment] 2018-03-02 21:17
Hey @ethanwhite - I am not aware of any blocking of user agent. Also, I was unable to reproduce your observations of 403s when downloading the interactions.tsv.gz file. 

Please provide an isolated python code so I can reproduce the issue.

Thanks!

**Comment by ethanwhite** [comment] 2018-03-03 17:15
Thanks @jhpoelen. Here's code to reproduce, but it doesn't seem to be agent blocking.

```python
from urllib.request import urlretrieve

urlretrieve("https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/interactions.tsv.gz")
```

If I do the same download using `requests` it works:

```
import requests

r = requests.get('https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/interactions.tsv.gz', stream=True)

with open('interactions.tsv.gz', 'wb') as f:
    for chunk in r.iter_content():
            f.write(chunk)
```

so I'm not sure what it is about this particular url that is causing issues using `urllib` (it's the only one out of hundreds that we work with).

Here's the full traceback for the record, but this seems like it's probably something we should be solving on our end:

```python
HTTPError                                 Traceback (most recent call last)
<ipython-input-2-5a4a41fecf2b> in <module>()
----> 1 urlretrieve("https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/interactions.tsv.gz")

~/miniconda3/lib/python3.6/urllib/request.py in urlretrieve(url, filename, reporthook, data)
    246     url_type, path = splittype(url)
    247 
--> 248     with contextlib.closing(urlopen(url, data)) as fp:
    249         headers = fp.info()
    250 

~/miniconda3/lib/python3.6/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    221     else:
    222         opener = _opener
--> 223     return opener.open(url, data, timeout)
    224 
    225 def install_opener(opener):

~/miniconda3/lib/python3.6/urllib/request.py in open(self, fullurl, data, timeout)
    530         for processor in self.process_response.get(protocol, []):
    531             meth = getattr(processor, meth_name)
--> 532             response = meth(req, response)
    533 
    534         return response

~/miniconda3/lib/python3.6/urllib/request.py in http_response(self, request, response)
    640         if not (200 <= code < 300):
    641             response = self.parent.error(
--> 642                 'http', request, response, code, msg, hdrs)
    643 
    644         return response

~/miniconda3/lib/python3.6/urllib/request.py in error(self, proto, *args)
    568         if http_err:
    569             args = (dict, 'default', 'http_error_default') + orig_args
--> 570             return self._call_chain(*args)
    571 
    572 # XXX probably also want an abstract factory that knows when it makes

~/miniconda3/lib/python3.6/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    502         for handler in handlers:
    503             func = getattr(handler, meth_name)
--> 504             result = func(*args)
    505             if result is not None:
    506                 return result

~/miniconda3/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: Forbidden
```

**Comment by jhpoelen** [comment] 2018-03-26 23:56
@ethanwhite Please let me know if it appears to be an issue on our end and I'll re-open the issue. Meanwhile, closing it.

**Closed by jhpoelen** 2018-03-26 23:56 UTC

**Comment by ethanwhite** [comment] 2018-03-27 00:06
The redirect was causing and issue for Python's `urllib`. We patched it by just using the destination url on S3:

https://github.com/weecology/retriever/pull/1096

Motivated by this we're going to go ahead and upgrade to using `requests` to avoid these sorts of issues in the future. Thanks for your help debugging. Much appreciated.
